version: "3.9"

services:
  db:
    container_name: fasttodo-db
    image: postgres:14.8-alpine
    command: postgres -c stats_temp_directory=/tmp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fasttodo
    ports:
      - 5432:5432
    volumes:
      - ./tmp/data:/var/lib/postgresql/data

  app:
    container_name: fasttodo-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/fasttodo
    depends_on:
      - db
    env_file:
      - ./backend/.env